name: Sync Docs to Mirror

on:
  push:
    branches: [ master, dev, docs ]
    paths:
      - 'Docs/**'
      - 'Docs/DataTables/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1) 원본 레포 체크아웃 (형의 본 레포)
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) 미러 레포 체크아웃 (Docs만 덮어쓰고 .github은 유지)
      - name: Checkout mirror repo (keep .github)
        uses: actions/checkout@v4
        with:
          repository: ifnotall/PROJECT_Black_Docs
          token: ${{ secrets.DOCS_PUSH_TOKEN }}
          path: mirror

      # 3) Docs만 동기화 (삭제/갱신 동기화, .github 보존)
      - name: Sync Docs into mirror
        run: |
          mkdir -p mirror/Docs
          rsync -a --delete Docs/ mirror/Docs/

      # 4) 커밋 & 푸시 (변경 없으면 스킵)
      - name: Commit & push to mirror
        run: |
          cd mirror
          git config user.name "DocsSyncBot"
          git config user.email "docs-sync@users.noreply.github.com"
          git add Docs
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            # 원본 커밋 메시지를 재사용, 없으면 기본 메시지
            MSG="${{ github.event.head_commit.message }}"
            if [ -z "$MSG" ]; then MSG="docs sync"; fi
            git commit -m "$MSG"
            git push origin HEAD:main
          fi
